# Generated by Django 6.0.5 on 2026-05-13 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ['friend__username']},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_group',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='is_public',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_type',
            field=models.CharField(choices=[('public', 'Public chat'), ('direct', 'Private chat'), ('group', 'Group chat')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
