# Generated by Django 6.0.5 on 2026-05-13 16:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=accounts.models.default_profile_pic, null=True, upload_to='profile_pics/', verbose_name='Профайл зураг'),
        ),
    ]
